### PR TITLE
A few refactorings and tooling upkeep

### PR DESCRIPTION
**Pull request by thunderbiscuit**
### Description
This PR addresses the issues outlined in #38.

### Notes to the reviewers
This PR is a collection of small improvements and updates to the library. 

~Do not merge before a hotfix for the tests has been merged (problems with the temporary directories).~ _Edit: this is fixed by bd7f300._ To test locally before the hotfix has been issued, simply add the `@Before` annotation to the `cleanupTestDataDir()` method like so:
```kotlin
@Before
fun cleanupTestDataDir() {
    File(getTestDataDir()).deleteRecursively()
}
```

### Checklists
- [x] b4cc0fa brings the Rust crate in its own directory, to better segregate the ideas that (a) Rust is being used to build a native library for each target architecture, and (b) those libraries are then used in the android and jvm versions of bdk-jni as dependencies. The Rust crate is an internal implementation detail of bdk-jni, and the file layout reflecting that is I think is a small but neat improvement in my opinion. Not sure about the name of the new directory (native-libs). Please let me know if you have suggestions for a name that would be more appropriate. Candidate names could be `rust`, `crate`, `native-libraries`, etc.
- [x] 5491deb, f150168, and f151c9e bring the tooling up to speed with the latest versions (Gradle wrapper, Gradle plugin, Koltin plugin)
- [x] d36b24c brings the license on par with the bitcoindevkit MIT/Apache 2.0 dual-license.
- [x] 330ffdc addresses small docs issues (tasks 7 and 8 in #38)
- [x] 3e6c716 addresses task 6 in #38.

### All Submissions:
* [x] I've signed all my commits

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
@notmandatory I think this PR needs a few docs changes (which I'll add today hopefully), but otherwise is starting to look good. Rust in it's own directory, updated tooling, updated license. We're hopefully gearing up for `v0.3.0`!

The only thing is it can't be merged before the hotfix for the test issue, and I think you had a solution in mind for the temporary directories created in the tests rather than just adding the `@Before` annotation, but I'm just not sure what it was. Let me know if I can be of any help.

**Comment by notmandatory** [comment]
I think I fixed the test issue by creating a unit test data directory for each one and cleaning it up after see bd7f300fa1fadd4330ffe53b5576a06c363e606e. It's a bit verbose but should work for CI and locally. Give it a try and let me know if it works locally for you.

**Comment by thunderbiscuit** [comment]
Everything builds fully for me.

I've fixed the docs slightly to mention the minimum JDK to be 11, and mention that the Rust version used to build is `1.53.0`, addressing tasks 7 and 8 in #38.

I think this PR is ready for review/merge.

**Comment by thunderbiscuit** [comment]
All right I couldn't resist and added some stuff in the docs. I don't think they are in their final form yet; one of my mentees had troubles understanding how this whole repo came together and the different parts that make it happen (he was building just the JVM. I want to make sure that's better outlined for the newcomers, but for now I think this is a small improvement.

Commit 3e6c716 addresses task 6 in #38.

**Comment by afilini** [comment]
I don't remember exactly how we've done the re-licensing for BDK, but aren't we somehow supposed to ask for permission to every contributor of the project?

At least here there shouldn't be all that many..

**Pull request merged**
